{
 "title": "aiDAPTIV Log Storage",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Service",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: \"phisonai\",\r\n    tag: \"serviceId\",\r\n    predicate: (r) => r._measurement == \"n_log\",\r\n    start: v.timeRangeStart,\r\n    stop:v.timeRangeStop\r\n)"
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "FlowID",
    "label": "Flow ID",
    "query": {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\" and r[\"flowId\"] != \"\")\r\n  |> group(columns: [\"flowId\"], mode: \"by\")\r\n  |> unique(column: \"flowId\")\r\n  |> map(fn: (r) => ({flowId: r.flowId}))"
    }
   },
   {
    "name": "GPU_Node",
    "label": "GPU Node",
    "query": {
     "query": "label_values(nvidia_gpu_info,node)"
    }
   },
   {
    "name": "GPU",
    "query": {
     "query": "label_values(nvidia_gpu_info,cardMinor)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "model_name", "label": "Model Name", "query": { "query": "label_values(model_name)" } },
   {
    "name": "TimeTo",
    "label": "Time To",
    "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\")\r\n  |> filter(fn: (r) => r[\"flowId\"] == \"${FlowID}\")\r\n  |> last()\r\n  |> keep(columns: [\"_time\"])\r\n    |> map(fn: (r) => ({ r with _time: int(v: r._time)/1000000+600000}))\r\n"
   },
   {
    "name": "TimeFrom",
    "label": "Time From",
    "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\")\r\n  |> filter(fn: (r) => r[\"flowId\"] == \"${FlowID}\")\r\n  |> first()\r\n  |> keep(columns: [\"_time\"])\r\n  |> map(fn: (r) => ({ r with _time: int(v: r._time)/1000000-600000}))"
   },
   {
    "name": "ErrorFlowCount",
    "label": "Error Flow Count",
    "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\" and r[\"flowId\"] != \"\")\r\n  |> filter(fn: (r) => r[\"level\"] == \"Error\")\r\n  |> group(columns: [\"flowId\"], mode: \"by\")\r\n  |> unique(column:\"flowId\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> sum()\r\n"
   },
   {
    "name": "FlowCount",
    "label": "Flow Count",
    "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\" and r[\"flowId\"] != \"\")\r\n  |> group(columns: [\"flowId\"], mode: \"by\")\r\n  |> unique(column:\"flowId\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> sum()\r\n"
   },
   {
    "name": "UserCount",
    "label": "User Count",
    "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\" and r[\"userId\"] != \"\")\r\n  |> group(columns: [\"userId\"], mode: \"by\")\r\n  |> unique(column:\"userId\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> sum()\r\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Error Flow Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$ErrorFlowCount/$FlowCount*100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\" and r[\"userId\"] != \"\")   \r\n  |> filter(fn: (r) => r.serviceId =~ /^${Service:regex}$/)\r\n  |> group(columns: [\"userId\"], mode: \"by\")\r\n  |> unique(column:\"userId\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> aggregateWindow(every: 30m, fn: sum)\r\n  |> cumulativeSum(columns: [\"_value\"]) \r\n"
    },
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: -7d, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\" and r[\"userId\"] != \"\")   \r\n  |> filter(fn: (r) => r.serviceId =~ /^${Service:regex}$/)\r\n  |> group(columns: [\"userId\"], mode: \"by\")\r\n  |> unique(column:\"userId\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> aggregateWindow(every: 30m, fn: sum)\r\n  |> cumulativeSum(columns: [\"_value\"]) \r\n"
    },
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: -1d, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\" and r[\"userId\"] != \"\")   \r\n  |> filter(fn: (r) => r.serviceId =~ /^${Service:regex}$/)\r\n  |> group(columns: [\"userId\"], mode: \"by\")\r\n  |> unique(column:\"userId\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> aggregateWindow(every: 30m, fn: sum)\r\n  |> cumulativeSum(columns: [\"_value\"]) \r\n"
    }
   ]
  },
  {
   "title": "User Count Record",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\" and r[\"userId\"] != \"\")   \r\n  |> filter(fn: (r) => r.serviceId =~ /^${Service:regex}$/)\r\n  |> group(columns: [\"userId\"], mode: \"by\")\r\n  |> unique(column:\"userId\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> cumulativeSum(columns: [\"_value\"]) \r\n  |> aggregateWindow(every: 20m, fn: count)"
    }
   ]
  },
  {
   "title": "Flow Count Record",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\" and r[\"flowId\"] != \"\")\r\n  |> filter(fn: (r) => r.serviceId =~ /^${Service:regex}$/)\r\n  |> group(columns: [\"flowId\"], mode: \"by\")\r\n  |> unique(column:\"flowId\")\r\n  |> map(fn: (r) => ({_time: r._time, _value: 1}))\r\n  |> cumulativeSum(columns: [\"_value\"]) \r\n  |> aggregateWindow(every: 20m, fn: count)"
    }
   ]
  },
  {
   "title": "Average Flow Count of Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "$FlowCount/$UserCount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "aiDAPTIV Log Record",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"phisonai\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"n_log\")\r\n  |> filter(fn: (r) => r.serviceId =~ /^${Service:regex}$/)\r\n  |> filter(fn: (r) => r.flowId =~ /^${FlowID:regex}$/)\r\n  |> keep(columns: [\"_time\", \"level\",\"errorCode\",\"version\", \"_value\", \"callSite\",\"serviceId\",\"ip\",\"flowId\",\"userId\"])\r\n  |> map(fn: (r) => ({ r with t_start: int(v: r._time)/1000000-600000}))\r\n  |> map(fn: (r) => ({ r with t_end: int(v: r._time)/1000000+600000}))\r\n|> group()"
    }
   ]
  },
  { "title": "Flow Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Process list in flow",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "filters": [
      { "id": "43867fa8", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "query": "{name=\"${FlowID}\"}",
     "spss": 10,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Process handling time",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 20,
     "query": "{name=\"${FlowID}\"}",
     "tableType": "traces"
    }
   ]
  },
  { "title": "vLLM Model", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Token Throughput",
   "type": "timeseries",
   "description": "Number of tokens processed per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(vllm:prompt_tokens_total{model_name=\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Prompt Tokens/Sec"
    },
    {
     "expr": "rate(vllm:generation_tokens_total{model_name=\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Generation Tokens/Sec"
    }
   ]
  },
  {
   "title": "E2E Request Latency",
   "type": "timeseries",
   "description": "End to end request latency measured in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "rate(vllm:e2e_request_latency_seconds_sum{model_name=\"$model_name\"}[$__rate_interval])\n/\nrate(vllm:e2e_request_latency_seconds_count{model_name=\"$model_name\"}[$__rate_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  { "title": "Basic Hardware Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}