{
 "title": "Docker Container Dashboard",
 "description": "Dashboard with details of the container metrics and host OS metrics.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datacenter", "label": "datacenter", "query": "${VAR_DATACENTER}" },
   {
    "name": "environment",
    "query": {
     "query": "label_values(cadvisor_version_info, env)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(cadvisor_version_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(cadvisor_version_info{env=~\"$environment\",job=~\"$job\"}, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,2m,3m,5m,10m,30m" },
   {
    "name": "id",
    "label": "ID",
    "query": {
     "query": "label_values(container_memory_usage_bytes{name=~\"$containers\", instance=~\"$node\"}, id)"
    }
   },
   {
    "name": "containers",
    "label": "Containers",
    "query": {
     "query": "label_values(container_memory_usage_bytes{instance=~\"$node\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{container_label_com_docker_compose_container_number=~\"1\",instance=~\"$node\"}[5m]))"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\",instance=~\"$node\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\",instance=~\"$node\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Docker Containers Infomation",
   "type": "table",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "time() - max(container_last_seen{container_label_com_docker_compose_container_number=~\"1\",name!=\"\", id!=\"\", name=~\"$containers\"}) by (name, id)"
    },
    {
     "expr": "max(container_start_time_seconds{container_label_com_docker_compose_container_number=~\"1\",name!=\"\",id!=\"\",instance=~\"$node\", name=~\"$containers\"}) by (name, id) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\", id!=\"\", name=~\"$containers\"}[$interval])) by (name, id) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(container_memory_usage_bytes{name!=\"\", id!=\"\", name=~\"$containers\"}) by (name, id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$containers\",instance=~\"$node\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used Memory per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_container_number=~\"1\",name!=\"\", id!=\"\",name=~\"$containers\",instance=~\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"$containers\",instance=~\"$node\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=~\"$containers\",instance=~\"$node\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}