{
 "title": "Phison Ai100 & Nvidia GPU",
 "tags": [ "nvidia" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(nvidia_gpu_info,instance)"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "label_values(nvidia_gpu_info,cardMinor)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pro Suite Nodes Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU 總數量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nvidia_gpu_power_usage{instance=~\"$instance.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU 使用狀態",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nvidia_gpu_power_usage{instance=~\"$instance.*\"})",
     "legendFormat": "Total GPU cards"
    },
    {
     "expr": "count(nvidia_gpu_available{instance=~\"$instance.*\"} == 1)",
     "legendFormat": "Inused GPUs"
    },
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Total GPU Avg Utilization",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(nvidia_gpu_utilization_by_card{instance=~\"$instance.*\", cardMinor=~\"$gpu\"}[$__range]))"
    }
   ]
  },
  {
   "title": "GPU 資源使用率",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(nvidia_gpu_utilization_by_card{instance=~\"$instance.*\", cardMinor=~\"$gpu\"}[$__range]))",
     "legendFormat": "Total GPU Utilization"
    },
    {
     "expr": "avg(nvidia_gpu_memory_utilization_by_card{instance=~\"$instance.*\", cardMinor=~\"$gpu\"})",
     "legendFormat": "Total GPU Memory Utilization"
    },
    {
     "expr": "sum(nvidia_gpu_power_usage{instance=~\"$instance.*\", cardMinor=~\"$gpu\", }) / sum(nvidia_gpu_power_limit{instance=~\"$instance.*\", cardMinor=~\"$gpu\"}) * 100",
     "legendFormat": "Total Power used percent"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nvidia_gpu_power_usage{instance=~\"$instance.*\"})"
    }
   ]
  },
  {
   "title": "Phison aiDAPTIV 數量",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nvme_percent_used{instance=~\"$instance.*\", firmware=~\"EIFZ.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Phison aiDAPTIV & GPU 資訊",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "max(nvidia_gpu_power_limit{instance=~\"$instance.*\"}) by (node, nvDriver, instance, cardName)"
    },
    {
     "expr": "count(nvidia_gpu_power_limit{instance=~\"$instance.*\"}) by (node, nvDriver, instance, cardName)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(nvme_temperature{instance=~\"$instance.*\", firmware=~\"EIFZ.*\"}) by (node, nvDriver, instance, cardName)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (node, nvDriver, instance, cardName) (nvidia_gpu_available{instance=~\"$instance.*\"} == 1) or vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (node, nvDriver, instance, cardName) (avg_over_time(nvidia_gpu_utilization_by_card{instance=~\"$instance.*\", cardMinor=~\"$gpu\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Phison aiDAPTIV 異常數量 ",
   "type": "stat",
   "description": "健康度<80%",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nvme_percent_used{instance=~\"$instance.*\", firmware=~\"EIFZ.*\"}>0 and nvme_percent_used{instance=~\"$instance.*\", firmware=~\"EIFZ.*\"}<=20)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Phison aiDAPTIVCache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "aiDAPTIVCache Temperature",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "nvme_temperature{instance=~\"$instance.*\", firmware=~\"EIFZ.*\"}",
       "legendFormat": "{{node}}-{{devicePath}}"
      }
     ]
    },
    {
     "title": "aiDAPTIVCache Information",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nvme_poweron_hours{instance=~\"$instance.*\", firmware=~\"EIFZ.*\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "(1-nvme_percent_used{instance=~\"$instance.*\", firmware=~\"EIFZ.*\"})*100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Nvidia GPU resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "nvidia_gpu_utilization_by_card{instance=~\"$instance.*\", cardMinor=~\"$gpu\"}",
       "legendFormat": "{{node}}-{{cardMinor}}"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "nvidia_gpu_memory_utilization_by_card{instance=~\"$instance.*\", cardMinor=~\"$gpu\"}",
       "legendFormat": "{{node}}-{{cardMinor}}"
      }
     ]
    },
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "nvidia_gpu_temperature{instance=~\"$instance.*\", cardMinor=~\"$gpu\"}",
       "legendFormat": "{{node}}-{{cardMinor}}"
      }
     ]
    },
    {
     "title": "GPU Power Usage",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "nvidia_gpu_power_usage{instance=~\"$instance.*\", cardMinor=~\"$gpu\"}",
       "legendFormat": "{{node}}-{{cardMinor}}"
      }
     ]
    },
    {
     "title": "GPU card information",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "nvidia_gpu_info{instance=~\"$instance.*\", cardMinor=~\"$gpu\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}